name: checkout
on: workflow_dispatch

jobs:
  no-checkout:
    runs-on: ubuntu_latest
    steps:
      - name: check file list
        run: cat README.md

  checkout:
    runs-on: ubuntu_latest
    steps:
      - name: use checkout action
        uses: actions/checkout@v4
      - name: check file list
        run: cat README.md
