name: pull-request-workflow
on: pull_request


jobs:
  PR-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
    steps:
      - name: step2
        run: |
          echo hello world
          echo github actions